using System.Collections.Generic;

namespace Tamarillo.Classes.Helpers {

    internal static class MapInfo {

        public static List<string> FilteredMaps = new List<string>() {
            "005_intro.map",
            "00a_introduction.map",
            "010_jungle.map",
            "01a_tutorial.map",
            "01b_spacestation.map",
            "020_base.map",
            "030_outskirts.map",
            "03a_oldmombasa.map",
            "03b_newmombasa.map",
            "040_voi.map",
            "04a_gasgiant.map",
            "04b_floodlab.map",
            "050_floodvoi.map",
            "05a_deltaapproach.map",
            "05b_deltatowers.map",
            "06a_sentinelwalls.map",
            "06b_floodzone.map",
            "070_waste.map",
            "07a_highcharity.map",
            "07b_forerunnership.map",
            "08a_deltacliffs.map",
            "08b_deltacontrol.map",
            "100_citadel.map",
            "110_hc.map",
            "120_halo.map",
            "130_epilogue.map",
            "a10.map",
            "a30.map",
            "a50.map",
            "b30.map",
            "b40.map",
            "bitmaps.map",
            "c10.map",
            "c20.map",
            "c40.map",
            "campaign.map",
            "cex_ff_halo.map",
            "d20.map",
            "d40.map",
            "dlc01_engine.map",
            "dlc01_engine.map",
            "dlc01_factory.map",
            "dlc_dejunkyard.map",
            "dlc_forge_island.map",
            "ff10_prototype.map",
            "ff151_mezzanine.map",
            "ff152_vortex.map",
            "ff153_caverns.map",
            "ff154_hillside.map",
            "ff155_breach.map",
            "ff20_courtyard.map",
            "ff30_waterfront.map",
            "ff45_corvette.map",
            "ff50_park.map",
            "ff60_airview.map",
            "ff60_icecave.map",
            "ff70_holdout.map",
            "ff81_courtyard.map",
            "ff82_scurve.map",
            "ff84_temple.map",
            "ff86_sniperalley.map",
            "ff87_chopperbowl.map",
            "ff90_fortsw.map",
            "ff91_complex.map",
            "ff92_valhalla.map",
            "ff_unearthed.map",
            "m020.map",
            "m05.map",
            "m05_prologue.map",
            "m10.map",
            "m10_crash.map",
            "m20.map",
            "m30.map",
            "m30_cryptum.map",
            "m35.map",
            "m40_invasion.map",
            "m45.map",
            "m50.map",
            "m52.map",
            "m60.map",
            "m60_rescue.map",
            "m70.map",
            "m70_a.map",
            "m70_bonus.map",
            "m70_liftoff.map",
            "m80_delta.map",
            "m90_sacrifice.map",
            "m95_epilogue.map",
            "mainmenu.map",
            "shared.map",
            "single_player_shared.map",
            "ui.map"
        };

        public static string GetMapName(Game type, string filename) {
            try {
                return MapNames[type][filename.Replace("remove_", "").Replace("backup_", "")];
            }
            catch {
                return "map_unknown";
            }
        }
        public static string GetMapImage(Game type, string filename) {
            try {
                return MapImages[type][filename.Replace("remove_", "").Replace("backup_", "")];
            }
            catch {
                return "map_unknown";
            }
        }

        public static Dictionary<Game, Dictionary<string, string>> MapImages {
            get; set;
        }
        = new Dictionary<Game, Dictionary<string, string>>() {
            { Game.H1, new Dictionary<string, string>() {
                { "beavercreek",    "h1_map_battlecreek" },
                { "bloodgulch",     "h1_map_bloodgulch" },
                { "boardingaction", "h1_map_boardingaction" },
                { "chillout",       "h1_map_chillout" },
                { "putput",         "h1_map_chirontl34" },
                { "damnation",      "h1_map_damnation" },
                { "dangercanyon",   "h1_map_dangercanyon" },
                { "deathisland",    "h1_map_deathisland" },
                { "carousel",       "h1_map_derelict" },
                { "gephyrophobia",  "h1_map_gephyrophobia" },
                { "hangemhigh",     "h1_map_hangemhigh" },
                { "icefields",      "h1_map_icefields" },
                { "infinity",       "h1_map_infinity" },
                { "longest",        "h1_map_longest" },
                { "prisoner",       "h1_map_prisoner" },
                { "ratrace",        "h1_map_ratrace" },
                { "sidewinder",     "h1_map_sidewinder" },
                { "timberland",     "h1_map_timberland" },
                { "wizard",         "h1_map_wizard" }
            } },
            { Game.H2, new Dictionary<string, string>() {
                { "ascension",      "h2_map_ascension" },
                { "backwash",       "h2_map_backwash" },
                { "beavercreek",    "h2_map_beavercreek" },
                { "burial_mounds",  "h2_map_burialmounds" },
                { "coagulation",    "h2_map_coagulation" },
                { "colossus",       "h2_map_colossus" },
                { "containment",    "h2_map_containment" },
                { "cyclotron",      "h2_map_ivorytower" },
                { "derelict",       "h2_map_desolation" },
                { "street_sweeper", "h2_map_district" },
                { "elongation",     "h2_map_elongation" },
                { "foundation",     "h2_map_foundation" },
                { "gemini",         "h2_map_gemini" },
                { "headlong",       "h2_map_headlong" },
                { "lockout",        "h2_map_lockout" },
                { "midship",        "h2_map_midship" },
                { "dune",           "h2_map_relic" },
                { "deltatap",       "h2_map_sanctuary" },
                { "highplains",     "h2_map_tombstone" },
                { "triplicate",     "h2_map_terminal" },
                { "turf",           "h2_map_turf" },
                { "needle",         "h2_map_uplift" },
                { "waterworks",     "h2_map_waterworks" },
                { "warlock",        "h2_map_warlock" },
                { "zanzibar",       "h2_map_zanzibar" }
            } },
            { Game.H2A, new Dictionary<string, string>() {
                { "ca_forge_skybox01", "h2a_map_awash" },
                { "ca_forge_skybox02", "h2a_map_nebula" },
                { "ca_forge_skybox03", "h2a_map_skyward" },
                { "ca_ascension",      "h2a_map_zenith" },
                { "ca_coagulation",    "h2a_map_bloodline" },
                { "ca_lockout",        "h2a_map_lockdown" },
                { "ca_relic",          "h2a_map_remnant" },
                { "ca_sanctuary",      "h2a_map_shrine" },
                { "ca_warlock",        "h2a_map_warlord" },
                { "ca_zanzibar",       "h2a_map_stonetown" }
            } },
            { Game.H3, new Dictionary<string, string>() {
                { "descent",       "h3_map_assembly" },
                { "sidewinder",    "h3_map_avalanche" },
                { "lockout",       "h3_map_blackout" },
                { "fortress",      "h3_map_fortress" },
                { "chillout",      "h3_map_coldstorage" },
                { "construct",     "h3_map_construct" },
                { "docks",         "h3_map_longshore" },
                { "s3d_edge",      "h3_map_s3d_edge" },
                { "salvation",     "h3_map_epitaph" },
                { "warehouse",     "h3_map_foundry" },
                { "ghosttown",     "h3_map_ghosttown" },
                { "guardian",      "h3_map_guardian" },
                { "midship",       "h3_map_heretic" },
                { "deadlock",      "h3_map_highground" },
                { "s3d_turf",      "h3_map_s3d_turf" },
                { "isolation",     "h3_map_isolation" },
                { "zanzibar",      "h3_map_lastresort" },
                { "chill",         "h3_map_narrows" },
                { "spacecamp",     "h3_map_orbital" },
                { "armory",        "h3_map_ratsnest" },
                { "sandbox",       "h3_map_sandbox" },
                { "shrine",        "h3_map_sandtrap" },
                { "snowbound",     "h3_map_snowbound" },
                { "bunkerworld",   "h3_map_standoff" },
                { "cyberdyne",     "h3_map_thepit" },
                { "riverworld",    "h3_map_valhalla" },
                { "s3d_waterfall", "h3_map_s3d_waterfall" }
            } },
            { Game.HR, new Dictionary<string, string>() {
                { "dlc_slayer",        "hr_map_anchor9" },
                { "cex_beaver_creek",  "hr_map_battlecanyon" },
                { "50_panopticon",     "hr_map_boardwalk" },
                { "70_boneyard",       "hr_map_boneyard" },
                { "cex_headlong",      "hr_map_breakneck" },
                { "dlc_invasion",      "hr_map_breakpoint" },
                { "condemned",         "hr_map_condemned" },
                { "45_launch_station", "hr_map_countdown" },
                { "forge_halo",        "hr_map_forgeworld" },
                { "trainingpreserve",  "hr_map_highlands" },
                { "cex_hangemhigh",    "hr_map_highnoon" },
                { "cex_damnation",     "hr_map_penance" },
                { "30_settlement",     "hr_map_powerhouse" },
                { "52_ivory_tower",    "hr_map_reflection" },
                { "cex_timberland",    "hr_map_ridgeline" },
                { "35_island",         "hr_map_spire" },
                { "cex_prisoner",      "hr_map_solitary" },
                { "20_sword_slayer",   "hr_map_swordbase" },
                { "dlc_medium",        "hr_map_tempest" },
                { "45_aftship",        "hr_map_zealot" }
            } },
            { Game.H4, new Dictionary<string, string>() {
                { "ca_blood_cavern",   "h4_map_abandon" },
                { "ca_warhouse",       "h4_map_adrift" },
                { "z05_cliffside",     "h4_map_complex" },
                { "ca_spiderweb",      "h4_map_daybreak" },
                { "ca_forge_erosion",  "h4_map_erosion" },
                { "ca_blood_crash",    "h4_map_exile" },
                { "dlc_forge_island",  "h4_map_forgeisland" },
                { "zd_02_grind",       "h4_map_harvest" },
                { "wraparound",        "h4_map_haven" },
                { "ca_forge_bonanza",  "h4_map_impact" },
                { "ca_port",           "h4_map_landfall" },
                { "ca_gore_valley",    "h4_map_longbow" },
                { "ca_canyon",         "h4_map_meltdown" },
                { "ca_deadlycrossing", "h4_map_monolith" },
                { "ca_basin",          "h4_map_outcast" },
                { "ca_highrise",       "h4_map_perdition" },
                { "ca_creeper",        "h4_map_pitfall" },
                { "z11_valhalla",      "h4_map_ragnarok" },
                { "ca_forge_ravine",   "h4_map_ravine" },
                { "dlc_dejewel",       "h4_map_shatter" },
                { "ca_rattler",        "h4_map_skyline" },
                { "ca_tower",          "h4_map_solace" },
                { "ca_dropoff",        "h4_map_vertigo" },
                { "ca_redoubt",        "h4_map_vortex" },
                { "dlc_dejunkyard",    "h4_map_wreckage" }
            } }
        };
        public static Dictionary<Game, Dictionary<string, string>> MapNames {
            get; set;
        }
= new Dictionary<Game, Dictionary<string, string>>() {
            { Game.H1, new Dictionary<string, string> {
            { "beavercreek", "Battle Creek" },
            { "bloodgulch", "Blood Gulch" },
            { "boardingaction", "Boarding Action" },
            { "chillout", "Chill Out" },
            { "putput", "Chiron TL-34" },
            { "damnation", "Damnation" },
            { "dangercanyon", "Danger Canyon" },
            { "deathisland", "Death Island" },
            { "carousel", "Derelict" },
            { "gephyrophobia", "Gephyrophobia" },
            { "hangemhigh", "Hang 'Em High" },
            { "icefields", "Ice Fields" },
            { "infinity", "Infinity" },
            { "longest", "Longest" },
            { "prisoner", "Prisoner" },
            { "ratrace", "Rat Race" },
            { "sidewinder", "Sidewinder" },
            { "timberland", "Timberland" },
            { "wizard", "Wizard" }
        } },
            { Game.H2, new Dictionary<string, string>
        {
            { "ascension", "Ascension" },
            { "backwash", "Backwash" },
            { "beaver_creek", "Beaver Creek" },
            { "burial_mounds", "Burial Mounds" },
            { "coagulation", "Coagulation" },
            { "colossus", "Colossus" },
            { "containment", "Containment" },
            { "desolation", "Desolation" },
            { "district", "District" },
            { "elongation", "Elongation" },
            { "foundation", "Foundation" },
            { "gemini", "Gemini" },
            { "headlong", "Headlong" },
            { "cyclotron", "Ivory Tower" },
            { "lockout", "Lockout" },
            { "midship", "Midship" },
            { "dune", "Relic" },
            { "deltatap", "Sanctuary" },
            { "highplains", "Tombstone" },
            { "triplicate", "Terminal" },
            { "turf", "Turf" },
            { "needle", "Uplift" },
            { "waterworks", "Waterworks" },
            { "warlock", "Warlock" },
            { "zanzibar", "Zanzibar" }
        } },
            { Game.H2A, new Dictionary<string, string>
        {
            { "ca_relic", "Remnant" },
            { "ca_ascension", "Zenith" },
            { "ca_warlock", "Warlord" },
            { "ca_zanzibar", "Stonetown" },
            { "ca_forge_skybox03", "Skyward" },
            { "ca_sanctuary", "Shrine" },
            { "ca_forge_skybox02", "Nebula" },
            { "ca_lockout", "Lockdown" },
            { "ca_coagulation", "Bloodline" },
            { "ca_forge_skybox01", "Awash" }
        } },
            { Game.H3, new Dictionary<string, string>() {
                { "descent", "Assembly" },
                { "sidewinder", "Avalanche" },
                { "lockout", "Blackout" },
                { "fortress", "Citadel" },
                { "chillout", "Cold Storage" },
                { "construct", "Construct" },
                { "docks", "Longshore" },
                { "s3d_edge", "Edge" },
                { "salvation", "Epitaph" },
                { "warehouse", "Foundry" },
                { "ghosttown", "Ghost Town" },
                { "guardian", "Guardian" },
                { "midship", "Heretic" },
                { "deadlock", "High Ground" },
                { "s3d_turf", "Icebox" },
                { "isolation", "Isolation" },
                { "zanzibar", "Last Resort" },
                { "chill", "Narrows" },
                { "spacecamp", "Orbital" },
                { "armory", "Rat's Nest" },
                { "sandbox", "Sandbox" },
                { "shrine", "Sandtrap" },
                { "snowbound", "Snowbound" },
                { "bunkerworld", "Standoff" },
                { "cyberdyne", "The Pit" },
                { "riverworld", "Valhalla" },
                { "s3d_waterfall", "Waterfall" }
            } },
            { Game.HR, new Dictionary<string, string>() {
                { "dlc_slayer", "Anchor 9" },
                { "cex_beaver_creek", "Battle Canyon" },
                { "50_panopticon", "Boardwalk" },
                { "70_boneyard", "Boneyard" },
                { "cex_headlong", "Breakneck" },
                { "dlc_invasion", "Breakpoint" },
                { "condemned", "Condemned" },
                { "45_launch_station", "Countdown" },
                { "forge_halo", "Forge World" },
                { "trainingpreserve", "Highlands" },
                { "cex_hangemhigh", "High Noon" },
                { "cex_damnation", "Penance" },
                { "30_settlement", "Powerhouse" },
                { "52_ivory_tower", "Reflection" },
                { "cex_timberland", "Ridgeline" },
                { "35_island", "Spire" },
                { "cex_prisoner", "Solitary" },
                { "20_sword_slayer", "Sword Base" },
                { "dlc_medium", "Tempest" },
                { "45_aftship", "Zealot" }
            } },
            { Game.H4, new Dictionary<string, string>() {
                { "ca_blood_cavern", "Abandon" },
                { "ca_warhouse", "Adrift" },
                { "z05_cliffside", "Complex" },
                { "ca_spiderweb", "Daybreak" },
                { "ca_forge_erosion", "Erosion" },
                { "ca_blood_crash", "Exile" },
                { "dlc_forge_island", "Forge Island" },
                { "zd_02_grind", "Harvest" },
                { "wraparound", "Haven" },
                { "ca_forge_bonanza", "Impact" },
                { "ca_port", "Landfall" },
                { "ca_gore_valley", "Longbow" },
                { "ca_canyon", "Meltdown" },
                { "ca_deadlycrossing", "Monolith" },
                { "ca_basin", "Outcast" },
                { "ca_highrise", "Perdition" },
                { "ca_creeper", "Pitfall" },
                { "z11_valhalla", "Ragnarok" },
                { "ca_forge_ravine", "Ravine" },
                { "dlc_dejewel", "Shatter" },
                { "ca_rattler", "Skyline" },
                { "ca_tower", "Solace" },
                { "ca_dropoff", "Vertigo" },
                { "ca_redoubt", "Vortex" },
                { "dlc_dejunkyard", "Wreckage" }
            } }
};

    }

}